services:
  server:
    image: iot-backend
    restart: unless-stopped
    networks:
      iot_network:
        ipv4_address: 192.168.0.4

networks:
  iot_network:
    external: true
    name: iot_network