FROM node:alpine AS build

WORKDIR /mnt

COPY . .

RUN npm install

RUN npm run build

FROM thistine/simple-http-server AS runner

WORKDIR /mnt

COPY --from=build /mnt/dist ./static

ENTRYPOINT [ "/app/serviceapifrontend" ]

EXPOSE 4000