# FROM oven/bun AS build
FROM node:lts AS build

WORKDIR /mnt

COPY . .

# RUN bun install
RUN npm install

# RUN bun run build
RUN npm run build

FROM thistine/simple-http-server AS runner

WORKDIR /mnt

COPY --from=build /mnt/dist ./static

ENTRYPOINT [ "/app/serviceapifrontend" ]

EXPOSE 4000